In [18]:
import pandas as pd

d={
    "CustomerID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Ahmed"]
}

e= pd.DataFrame(d)
e

   CustomerID   Name
0           1    Ali
1           2   Sara
2           3  Ahmed

In [19]:
e [["Name", "CustomerID"]]

    Name  CustomerID
0    Ali           1
1   Sara           2
2  Ahmed           3

In [ ]:
e.iloc[1] #Integer location based indexing

CustomerID       2
Name          Sara
Name: 1, dtype: object

In [28]:
e.iloc[1:3]

   CustomerID   Name
1           2   Sara
2           3  Ahmed

In [27]:
e.loc[1:2] #Label based indexing

   CustomerID   Name
1           2   Sara
2           3  Ahmed